### ISSUE TITLE
Fixed-Point to Binary and vice versa

### ISSUE THREAD

**Issue by AjinkyaBankar** [ZZZZzzzzac/numfi#2]
I want to convert the signed fixed-point to equivalent binary, manipulate some of the bits, and in the end, get the equivalent fixed-point number. How can I use `numfi` to accomplish the task?

**Comment by ZZZZzzzzac** [comment]
sry for late response. You can directly use bitwise logical  operator `&`(and) `|`(or) `~`(not) `^`(xor) and `<</>>`(shift) to numfi array.

`numfi.int` will give you its integer representation, and `numfi.bin/bin_` is binary representation, for example:
```python
x = numfi(113.7345,1,16,8)
x.int # 29116
x.bin # 0b0111000110111100
y = x & 0x00FF
y.bin # 0b0000000010111100
y.int # 188
y = x | 0x7F00
y.bin # 0b0111111110111100
y.int # 32700
y = ~x
y.bin # 0b1000111001000011
y.int # -29117
```
