### ISSUE TITLE
Negative fraction support

### ISSUE THREAD

**Issue by moux233** [ZZZZzzzzac/numfi#3]
Hi
Thank you for the package, I use it to interface with a FPGA.
I read in the docs: "Note that unlike matlab, negative fraction length is not supported".
I commented out the corresponding check in the numfi code.
Seems to work for simple input/output operations.
Could you comment on what will keep working/what will fail with negative fraction length?

**Comment by ZZZZzzzzac** [comment]
Back then I didn't fully understand negative fraction bits, so I just raise error when `f<0` for protection. 
But now both negative `f` and `i` are supported. :smiley:
